#!/usr/bin/env node
/**
 * Copies front-end dependencies from node_modules into the theme's static
 * directories.  Run via `npm run build` after `npm install`.
 */

const fs            = require('fs');
const path          = require('path');
const { execSync }  = require('child_process');

const root    = path.join(__dirname, '..');
const vendor  = path.join(root, 'htdocs/themes/StateDecoded2013/static/js/vendor');
const css     = path.join(root, 'htdocs/themes/StateDecoded2013/static/css');
const fonts   = path.join(root, 'htdocs/themes/StateDecoded2013/static/fonts/font-awesome');
const webfonts = path.join(root, 'htdocs/themes/StateDecoded2013/static/fonts/webfonts');
const scssDir = path.join(root, 'htdocs/themes/StateDecoded2013/static/scss');
const nm      = path.join(root, 'node_modules');

/*
 * The typefaces the theme uses, self-hosted rather than fetched from Google.
 *
 * Only the Latin subsets are shipped, in regular and bold, upright and italic:
 * that is what the stylesheets ask for, and every additional weight is another
 * file the reader has to download.
 */
const TYPEFACES = [
    { pkg: '@fontsource/lato',          prefix: 'lato' },
    { pkg: '@fontsource/merriweather',  prefix: 'merriweather' },
    { pkg: '@fontsource/crimson-text',  prefix: 'crimson-text' }
];

const FONT_WEIGHTS = ['400', '700'];
const FONT_STYLES  = ['normal', 'italic'];

function cp(src, dest) {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    console.log(`  ${path.relative(root, dest)}`);
}

function cpDir(srcDir, destDir) {
    fs.mkdirSync(destDir, { recursive: true });
    for (const f of fs.readdirSync(srcDir)) {
        const s = path.join(srcDir, f);
        const d = path.join(destDir, f);
        if (fs.statSync(s).isFile()) { cp(s, d); }
    }
}

/**
 * Copy the webfont files into the theme and generate the @font-face rules.
 *
 * The rules are taken from the CSS that each Fontsource package ships, rather
 * than written out here, so that details like unicode-range stay correct
 * without anyone having to maintain them. Only the URLs are rewritten, from
 * the package-relative "./files/…" to a path the browser can resolve against
 * the compiled stylesheet.
 */
function buildWebfonts() {
    console.log('Webfonts...');

    fs.mkdirSync(webfonts, { recursive: true });

    let faces = [
        '// Generated by scripts/build-assets.js. Do not edit.',
        '//',
        '// @font-face rules for the self-hosted webfonts, copied from the',
        '// Fontsource packages listed in package.json with their URLs rewritten',
        '// to point at static/fonts/webfonts/.',
        ''
    ];

    for (const face of TYPEFACES) {
        const pkgDir = path.join(nm, face.pkg);

        for (const weight of FONT_WEIGHTS) {
            for (const style of FONT_STYLES) {
                const cssName = style === 'italic'
                    ? `${weight}-italic.css`
                    : `${weight}.css`;
                const cssPath = path.join(pkgDir, cssName);

                if (!fs.existsSync(cssPath)) {
                    throw new Error(`Expected ${face.pkg}/${cssName}; the package layout may have changed.`);
                }

                /*
                 * Ship only the Latin subsets. Fontsource emits a separate
                 * @font-face per subset (Cyrillic, Vietnamese, and so on), and
                 * this site's content does not call for the rest.
                 */
                const blocks = (fs.readFileSync(cssPath, 'utf8')
                    .match(/@font-face\s*\{[^}]*\}/g) || [])
                    .filter(b => /-latin(-ext)?-/.test(b));

                if (blocks.length === 0) {
                    throw new Error(`No Latin @font-face rules found in ${face.pkg}/${cssName}.`);
                }

                for (const block of blocks) {
                    faces.push(block.replace(/url\(\.\/files\/([^)]+)\)/g,
                        'url("../fonts/webfonts/$1")'));
                    faces.push('');
                }
            }
        }

        /*
         * Copy the font files themselves: the Latin subsets, in the weights and
         * styles declared above.
         */
        const filesDir = path.join(pkgDir, 'files');
        for (const file of fs.readdirSync(filesDir)) {
            const wanted = new RegExp(
                `^${face.prefix}-latin(-ext)?-(${FONT_WEIGHTS.join('|')})-(${FONT_STYLES.join('|')})\\.woff2?$`
            );
            if (wanted.test(file)) {
                cp(path.join(filesDir, file), path.join(webfonts, file));
            }
        }
    }

    const facesPath = path.join(scssDir, 'dependencies/_webfonts.scss');
    fs.writeFileSync(facesPath, faces.join('\n'));
    console.log(`  ${path.relative(root, facesPath)}`);
}

console.log('Building front-end assets...');

// JavaScript
cp(path.join(nm, 'jquery/dist/jquery.min.js'),                  path.join(vendor, 'jquery.min.js'));
cp(path.join(nm, 'jquery-ui-dist/jquery-ui.min.js'),            path.join(vendor, 'jquery-ui.min.js'));
cp(path.join(nm, 'mousetrap/mousetrap.min.js'),                  path.join(vendor, 'mousetrap.min.js'));
cp(path.join(nm, 'qtip2/dist/jquery.qtip.min.js'),              path.join(vendor, 'jquery.qtip.min.js'));
cp(path.join(nm, 'qtip2/dist/jquery.qtip.min.map'),             path.join(vendor, 'jquery.qtip.min.map'));

// CSS
cp(path.join(nm, 'jquery-ui-dist/jquery-ui.css'),               path.join(css, 'jquery-ui.css'));
cp(path.join(nm, 'qtip2/dist/jquery.qtip.min.css'),             path.join(css, 'jquery.qtip.min.css'));

// jQuery UI sprite images — must sit in images/ relative to jquery-ui.css
cpDir(path.join(nm, 'jquery-ui-dist/images'),                   path.join(css, 'images'));

// Font Awesome fonts (the CSS is compiled into application.css via SCSS)
cpDir(path.join(nm, 'font-awesome/fonts'), fonts);

// Self-hosted webfonts, plus the @font-face rules that point at them
buildWebfonts();

// SCSS → CSS
const scssEntry = path.join(root, 'htdocs/themes/StateDecoded2013/static/scss/application.scss');
const cssOut    = path.join(root, 'htdocs/themes/StateDecoded2013/static/css/application.css');
const sass      = path.join(root, 'node_modules/.bin/sass');
console.log('Compiling SCSS...');
execSync(`"${sass}" "${scssEntry}" "${cssOut}" --style=compressed --no-source-map --silence-deprecation=import,slash-div,color-functions,global-builtin,function-units`, { stdio: 'inherit' });
console.log(`  ${path.relative(root, cssOut)}`);

console.log('Done.');
